[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_command = "polkadot"
chain_spec_command = "polkadot build-spec --chain rococo-local --disable-default-bootnode"

[relaychain.default_resources]
limits = { memory = "4G", cpu = "2" }
requests = { memory = "2G", cpu = "1" }

  [[relaychain.nodes]]
  name = "alice"
  args = [ "--alice", "-lparachain=debug,runtime=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  args = [ "--bob", "-lparachain=debug,runtime=debug"]

  [[relaychain.nodes]]
  name = "charlie"
  args = [ "--charlie", "-lparachain=debug,runtime=debug" ]

  [[relaychain.nodes]]
  name = "dave"
  args = [ "--dave", "-lparachain=debug,runtime=debug"]

  [[relaychain.nodes]]
  name = "ferdie"
  command = "kagome --wasm-execution Compiled --unsafe-cached-wavm-runtime"
  prometheus_prefix = "kagome"
  args = [ "--ferdie", "-lparachain=debug,runtime=debug" ]

  [[relaychain.nodes]]
  name = "eve"
  command = "kagome --wasm-execution Compiled --unsafe-cached-wavm-runtime"
  prometheus_prefix = "kagome"
  args = [ "--eve", "-lparachain=debug,runtime=debug"]

  [[relaychain.nodes]]
  name = "one"
  command = "kagome --wasm-execution Compiled --unsafe-cached-wavm-runtime"
  prometheus_prefix = "kagome"
  args = [ "--one", "-lparachain=debug,runtime=debug" ]

  [[relaychain.nodes]]
  name = "two"
  command = "kagome --wasm-execution Compiled --unsafe-cached-wavm-runtime"
  prometheus_prefix = "kagome"
  args = [ "--two", "-lparachain=debug,runtime=debug"]

[[parachains]]
id = 2000
add_to_genesis = false
genesis_state_generator = "undying-collator export-genesis-state --pov-size=100000 --pvf-complexity=1"

  [parachains.collator]
  name = "collator01"
  command = "undying-collator"
  args = ["-lparachain=debug", "--pov-size=100000", "--pvf-complexity=1", "--parachain-id=2000"]

[[parachains]]
id = 2001
add_to_genesis = false
genesis_state_generator = "undying-collator export-genesis-state --pov-size=100000 --pvf-complexity=10"

  [parachains.collator]
  name = "collator02"
  command = "undying-collator"
  args = ["-lparachain=debug", "--pov-size=100000", "--parachain-id=2001", "--pvf-complexity=10"]

[[parachains]]
id = 2002
add_to_genesis = false
genesis_state_generator = "undying-collator export-genesis-state --pov-size=100000 --pvf-complexity=100"

  [parachains.collator]
  name = "collator03"
  command = "undying-collator"
  args = ["-lparachain=debug", "--pov-size=100000", "--parachain-id=2002", "--pvf-complexity=100"]

[[parachains]]
id = 2003
add_to_genesis = false
genesis_state_generator = "undying-collator export-genesis-state --pov-size=20000 --pvf-complexity=300"

  [parachains.collator]
  name = "collator04"
  command = "undying-collator"
  args = ["-lparachain=debug", "--pov-size=20000", "--parachain-id=2003", "--pvf-complexity=300"]

[[parachains]]
id = 2004
add_to_genesis = false
genesis_state_generator = "undying-collator export-genesis-state --pov-size=100000 --pvf-complexity=300"

  [parachains.collator]
  name = "collator05"
  command = "undying-collator"
  args = ["-lparachain=debug", "--pov-size=100000", "--parachain-id=2004", "--pvf-complexity=300"]

[[parachains]]
id = 2005
add_to_genesis = false
genesis_state_generator = "undying-collator export-genesis-state --pov-size=20000 --pvf-complexity=400"

  [parachains.collator]
  name = "collator06"
  command = "undying-collator"
  args = ["-lparachain=debug", "--pov-size=20000",  "--pvf-complexity=400", "--parachain-id=2005"]

[[parachains]]
id = 2006
add_to_genesis = false
genesis_state_generator = "undying-collator export-genesis-state --pov-size=100000 --pvf-complexity=300"

  [parachains.collator]
  name = "collator07"
  command = "undying-collator"
  args = ["-lparachain=debug", "--pov-size=100000",  "--pvf-complexity=300", "--parachain-id=2006"]

[[parachains]]
id = 2007
add_to_genesis = false
genesis_state_generator = "undying-collator export-genesis-state --pov-size=100000 --pvf-complexity=300"

  [parachains.collator]
  name = "collator08"
  command = "undying-collator"
  args = ["-lparachain=debug", "--pov-size=100000",  "--pvf-complexity=300", "--parachain-id=2007"]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"